/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SuccessVideoAssetFavorites struct for SuccessVideoAssetFavorites
type SuccessVideoAssetFavorites struct {
	// datetime in RFC-3339 format (subset of ISO-8601) requiring a UTC time ending with Z (so -00:00 or +00-00 suffix NOT allowed). The datetime must have date and time, including seconds, e.g. 2016-01-15T09:23:34Z.
	AccountId *string `json:"account_id,omitempty"`
}

// NewSuccessVideoAssetFavorites instantiates a new SuccessVideoAssetFavorites object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccessVideoAssetFavorites() *SuccessVideoAssetFavorites {
	this := SuccessVideoAssetFavorites{}
	return &this
}

// NewSuccessVideoAssetFavoritesWithDefaults instantiates a new SuccessVideoAssetFavorites object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessVideoAssetFavoritesWithDefaults() *SuccessVideoAssetFavorites {
	this := SuccessVideoAssetFavorites{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *SuccessVideoAssetFavorites) GetAccountId() string {
	if o == nil || o.AccountId == nil {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuccessVideoAssetFavorites) GetAccountIdOk() (*string, bool) {
	if o == nil || o.AccountId == nil {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *SuccessVideoAssetFavorites) HasAccountId() bool {
	if o != nil && o.AccountId != nil {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *SuccessVideoAssetFavorites) SetAccountId(v string) {
	o.AccountId = &v
}

func (o SuccessVideoAssetFavorites) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountId != nil {
		toSerialize["account_id"] = o.AccountId
	}
	return json.Marshal(toSerialize)
}

type NullableSuccessVideoAssetFavorites struct {
	value *SuccessVideoAssetFavorites
	isSet bool
}

func (v NullableSuccessVideoAssetFavorites) Get() *SuccessVideoAssetFavorites {
	return v.value
}

func (v *NullableSuccessVideoAssetFavorites) Set(val *SuccessVideoAssetFavorites) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccessVideoAssetFavorites) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccessVideoAssetFavorites) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccessVideoAssetFavorites(val *SuccessVideoAssetFavorites) *NullableSuccessVideoAssetFavorites {
	return &NullableSuccessVideoAssetFavorites{value: val, isSet: true}
}

func (v NullableSuccessVideoAssetFavorites) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccessVideoAssetFavorites) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


