/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AlbumPayloadPublishInfoRemoteLinksView struct for AlbumPayloadPublishInfoRemoteLinksView
type AlbumPayloadPublishInfoRemoteLinksView struct {
	// Fully-formed URL to a location to view affiliated content (identified by remoteId) on the external service.
	Href *string `json:"href,omitempty"`
}

// NewAlbumPayloadPublishInfoRemoteLinksView instantiates a new AlbumPayloadPublishInfoRemoteLinksView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlbumPayloadPublishInfoRemoteLinksView() *AlbumPayloadPublishInfoRemoteLinksView {
	this := AlbumPayloadPublishInfoRemoteLinksView{}
	return &this
}

// NewAlbumPayloadPublishInfoRemoteLinksViewWithDefaults instantiates a new AlbumPayloadPublishInfoRemoteLinksView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlbumPayloadPublishInfoRemoteLinksViewWithDefaults() *AlbumPayloadPublishInfoRemoteLinksView {
	this := AlbumPayloadPublishInfoRemoteLinksView{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *AlbumPayloadPublishInfoRemoteLinksView) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlbumPayloadPublishInfoRemoteLinksView) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *AlbumPayloadPublishInfoRemoteLinksView) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *AlbumPayloadPublishInfoRemoteLinksView) SetHref(v string) {
	o.Href = &v
}

func (o AlbumPayloadPublishInfoRemoteLinksView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	return json.Marshal(toSerialize)
}

type NullableAlbumPayloadPublishInfoRemoteLinksView struct {
	value *AlbumPayloadPublishInfoRemoteLinksView
	isSet bool
}

func (v NullableAlbumPayloadPublishInfoRemoteLinksView) Get() *AlbumPayloadPublishInfoRemoteLinksView {
	return v.value
}

func (v *NullableAlbumPayloadPublishInfoRemoteLinksView) Set(val *AlbumPayloadPublishInfoRemoteLinksView) {
	v.value = val
	v.isSet = true
}

func (v NullableAlbumPayloadPublishInfoRemoteLinksView) IsSet() bool {
	return v.isSet
}

func (v *NullableAlbumPayloadPublishInfoRemoteLinksView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlbumPayloadPublishInfoRemoteLinksView(val *AlbumPayloadPublishInfoRemoteLinksView) *NullableAlbumPayloadPublishInfoRemoteLinksView {
	return &NullableAlbumPayloadPublishInfoRemoteLinksView{value: val, isSet: true}
}

func (v NullableAlbumPayloadPublishInfoRemoteLinksView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlbumPayloadPublishInfoRemoteLinksView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


