/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InvaildRequestMissingSubtypeWithFavorite struct for InvaildRequestMissingSubtypeWithFavorite
type InvaildRequestMissingSubtypeWithFavorite struct {
	Errors *InvaildRequestMissingSubtypeWithFavoriteErrors `json:"errors,omitempty"`
	Code *int32 `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewInvaildRequestMissingSubtypeWithFavorite instantiates a new InvaildRequestMissingSubtypeWithFavorite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvaildRequestMissingSubtypeWithFavorite() *InvaildRequestMissingSubtypeWithFavorite {
	this := InvaildRequestMissingSubtypeWithFavorite{}
	return &this
}

// NewInvaildRequestMissingSubtypeWithFavoriteWithDefaults instantiates a new InvaildRequestMissingSubtypeWithFavorite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvaildRequestMissingSubtypeWithFavoriteWithDefaults() *InvaildRequestMissingSubtypeWithFavorite {
	this := InvaildRequestMissingSubtypeWithFavorite{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *InvaildRequestMissingSubtypeWithFavorite) GetErrors() InvaildRequestMissingSubtypeWithFavoriteErrors {
	if o == nil || o.Errors == nil {
		var ret InvaildRequestMissingSubtypeWithFavoriteErrors
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvaildRequestMissingSubtypeWithFavorite) GetErrorsOk() (*InvaildRequestMissingSubtypeWithFavoriteErrors, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *InvaildRequestMissingSubtypeWithFavorite) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given InvaildRequestMissingSubtypeWithFavoriteErrors and assigns it to the Errors field.
func (o *InvaildRequestMissingSubtypeWithFavorite) SetErrors(v InvaildRequestMissingSubtypeWithFavoriteErrors) {
	o.Errors = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *InvaildRequestMissingSubtypeWithFavorite) GetCode() int32 {
	if o == nil || o.Code == nil {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvaildRequestMissingSubtypeWithFavorite) GetCodeOk() (*int32, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *InvaildRequestMissingSubtypeWithFavorite) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *InvaildRequestMissingSubtypeWithFavorite) SetCode(v int32) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InvaildRequestMissingSubtypeWithFavorite) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvaildRequestMissingSubtypeWithFavorite) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InvaildRequestMissingSubtypeWithFavorite) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InvaildRequestMissingSubtypeWithFavorite) SetDescription(v string) {
	o.Description = &v
}

func (o InvaildRequestMissingSubtypeWithFavorite) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableInvaildRequestMissingSubtypeWithFavorite struct {
	value *InvaildRequestMissingSubtypeWithFavorite
	isSet bool
}

func (v NullableInvaildRequestMissingSubtypeWithFavorite) Get() *InvaildRequestMissingSubtypeWithFavorite {
	return v.value
}

func (v *NullableInvaildRequestMissingSubtypeWithFavorite) Set(val *InvaildRequestMissingSubtypeWithFavorite) {
	v.value = val
	v.isSet = true
}

func (v NullableInvaildRequestMissingSubtypeWithFavorite) IsSet() bool {
	return v.isSet
}

func (v *NullableInvaildRequestMissingSubtypeWithFavorite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvaildRequestMissingSubtypeWithFavorite(val *InvaildRequestMissingSubtypeWithFavorite) *NullableInvaildRequestMissingSubtypeWithFavorite {
	return &NullableInvaildRequestMissingSubtypeWithFavorite{value: val, isSet: true}
}

func (v NullableInvaildRequestMissingSubtypeWithFavorite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvaildRequestMissingSubtypeWithFavorite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


