/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InvaildRequestGroupErrors struct for InvaildRequestGroupErrors
type InvaildRequestGroupErrors struct {
	Group []string `json:"group,omitempty"`
}

// NewInvaildRequestGroupErrors instantiates a new InvaildRequestGroupErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvaildRequestGroupErrors() *InvaildRequestGroupErrors {
	this := InvaildRequestGroupErrors{}
	return &this
}

// NewInvaildRequestGroupErrorsWithDefaults instantiates a new InvaildRequestGroupErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvaildRequestGroupErrorsWithDefaults() *InvaildRequestGroupErrors {
	this := InvaildRequestGroupErrors{}
	return &this
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *InvaildRequestGroupErrors) GetGroup() []string {
	if o == nil || o.Group == nil {
		var ret []string
		return ret
	}
	return o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvaildRequestGroupErrors) GetGroupOk() ([]string, bool) {
	if o == nil || o.Group == nil {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *InvaildRequestGroupErrors) HasGroup() bool {
	if o != nil && o.Group != nil {
		return true
	}

	return false
}

// SetGroup gets a reference to the given []string and assigns it to the Group field.
func (o *InvaildRequestGroupErrors) SetGroup(v []string) {
	o.Group = v
}

func (o InvaildRequestGroupErrors) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Group != nil {
		toSerialize["group"] = o.Group
	}
	return json.Marshal(toSerialize)
}

type NullableInvaildRequestGroupErrors struct {
	value *InvaildRequestGroupErrors
	isSet bool
}

func (v NullableInvaildRequestGroupErrors) Get() *InvaildRequestGroupErrors {
	return v.value
}

func (v *NullableInvaildRequestGroupErrors) Set(val *InvaildRequestGroupErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableInvaildRequestGroupErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableInvaildRequestGroupErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvaildRequestGroupErrors(val *InvaildRequestGroupErrors) *NullableInvaildRequestGroupErrors {
	return &NullableInvaildRequestGroupErrors{value: val, isSet: true}
}

func (v NullableInvaildRequestGroupErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvaildRequestGroupErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


