/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateAlbumRequest struct for UpdateAlbumRequest
type UpdateAlbumRequest struct {
	Payload *AlbumPayload `json:"payload,omitempty"`
}

// NewUpdateAlbumRequest instantiates a new UpdateAlbumRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAlbumRequest() *UpdateAlbumRequest {
	this := UpdateAlbumRequest{}
	return &this
}

// NewUpdateAlbumRequestWithDefaults instantiates a new UpdateAlbumRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAlbumRequestWithDefaults() *UpdateAlbumRequest {
	this := UpdateAlbumRequest{}
	return &this
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *UpdateAlbumRequest) GetPayload() AlbumPayload {
	if o == nil || o.Payload == nil {
		var ret AlbumPayload
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAlbumRequest) GetPayloadOk() (*AlbumPayload, bool) {
	if o == nil || o.Payload == nil {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *UpdateAlbumRequest) HasPayload() bool {
	if o != nil && o.Payload != nil {
		return true
	}

	return false
}

// SetPayload gets a reference to the given AlbumPayload and assigns it to the Payload field.
func (o *UpdateAlbumRequest) SetPayload(v AlbumPayload) {
	o.Payload = &v
}

func (o UpdateAlbumRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Payload != nil {
		toSerialize["payload"] = o.Payload
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateAlbumRequest struct {
	value *UpdateAlbumRequest
	isSet bool
}

func (v NullableUpdateAlbumRequest) Get() *UpdateAlbumRequest {
	return v.value
}

func (v *NullableUpdateAlbumRequest) Set(val *UpdateAlbumRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAlbumRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAlbumRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAlbumRequest(val *UpdateAlbumRequest) *NullableUpdateAlbumRequest {
	return &NullableUpdateAlbumRequest{value: val, isSet: true}
}

func (v NullableUpdateAlbumRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAlbumRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


