/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GenerateRenditions202Response struct for GenerateRenditions202Response
type GenerateRenditions202Response struct {
	// Base URL that can be prepended to the 'href' values in the 'links' to produce fully qualified URLs for future queries.
	Base *string `json:"base,omitempty"`
	Links map[string]interface{} `json:"links,omitempty"`
}

// NewGenerateRenditions202Response instantiates a new GenerateRenditions202Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateRenditions202Response() *GenerateRenditions202Response {
	this := GenerateRenditions202Response{}
	return &this
}

// NewGenerateRenditions202ResponseWithDefaults instantiates a new GenerateRenditions202Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateRenditions202ResponseWithDefaults() *GenerateRenditions202Response {
	this := GenerateRenditions202Response{}
	return &this
}

// GetBase returns the Base field value if set, zero value otherwise.
func (o *GenerateRenditions202Response) GetBase() string {
	if o == nil || o.Base == nil {
		var ret string
		return ret
	}
	return *o.Base
}

// GetBaseOk returns a tuple with the Base field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateRenditions202Response) GetBaseOk() (*string, bool) {
	if o == nil || o.Base == nil {
		return nil, false
	}
	return o.Base, true
}

// HasBase returns a boolean if a field has been set.
func (o *GenerateRenditions202Response) HasBase() bool {
	if o != nil && o.Base != nil {
		return true
	}

	return false
}

// SetBase gets a reference to the given string and assigns it to the Base field.
func (o *GenerateRenditions202Response) SetBase(v string) {
	o.Base = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GenerateRenditions202Response) GetLinks() map[string]interface{} {
	if o == nil || o.Links == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateRenditions202Response) GetLinksOk() (map[string]interface{}, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GenerateRenditions202Response) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]interface{} and assigns it to the Links field.
func (o *GenerateRenditions202Response) SetLinks(v map[string]interface{}) {
	o.Links = v
}

func (o GenerateRenditions202Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Base != nil {
		toSerialize["base"] = o.Base
	}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableGenerateRenditions202Response struct {
	value *GenerateRenditions202Response
	isSet bool
}

func (v NullableGenerateRenditions202Response) Get() *GenerateRenditions202Response {
	return v.value
}

func (v *NullableGenerateRenditions202Response) Set(val *GenerateRenditions202Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateRenditions202Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateRenditions202Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateRenditions202Response(val *GenerateRenditions202Response) *NullableGenerateRenditions202Response {
	return &NullableGenerateRenditions202Response{value: val, isSet: true}
}

func (v NullableGenerateRenditions202Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateRenditions202Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


