/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// GetCatalog403Response - struct for GetCatalog403Response
type GetCatalog403Response struct {
	AccessForbiddenAccountStateError *AccessForbiddenAccountStateError
	AccessForbiddenError *AccessForbiddenError
	InvalidAPIKeyError *InvalidAPIKeyError
}

// AccessForbiddenAccountStateErrorAsGetCatalog403Response is a convenience function that returns AccessForbiddenAccountStateError wrapped in GetCatalog403Response
func AccessForbiddenAccountStateErrorAsGetCatalog403Response(v *AccessForbiddenAccountStateError) GetCatalog403Response {
	return GetCatalog403Response{
		AccessForbiddenAccountStateError: v,
	}
}

// AccessForbiddenErrorAsGetCatalog403Response is a convenience function that returns AccessForbiddenError wrapped in GetCatalog403Response
func AccessForbiddenErrorAsGetCatalog403Response(v *AccessForbiddenError) GetCatalog403Response {
	return GetCatalog403Response{
		AccessForbiddenError: v,
	}
}

// InvalidAPIKeyErrorAsGetCatalog403Response is a convenience function that returns InvalidAPIKeyError wrapped in GetCatalog403Response
func InvalidAPIKeyErrorAsGetCatalog403Response(v *InvalidAPIKeyError) GetCatalog403Response {
	return GetCatalog403Response{
		InvalidAPIKeyError: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetCatalog403Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AccessForbiddenAccountStateError
	err = newStrictDecoder(data).Decode(&dst.AccessForbiddenAccountStateError)
	if err == nil {
		jsonAccessForbiddenAccountStateError, _ := json.Marshal(dst.AccessForbiddenAccountStateError)
		if string(jsonAccessForbiddenAccountStateError) == "{}" { // empty struct
			dst.AccessForbiddenAccountStateError = nil
		} else {
			match++
		}
	} else {
		dst.AccessForbiddenAccountStateError = nil
	}

	// try to unmarshal data into AccessForbiddenError
	err = newStrictDecoder(data).Decode(&dst.AccessForbiddenError)
	if err == nil {
		jsonAccessForbiddenError, _ := json.Marshal(dst.AccessForbiddenError)
		if string(jsonAccessForbiddenError) == "{}" { // empty struct
			dst.AccessForbiddenError = nil
		} else {
			match++
		}
	} else {
		dst.AccessForbiddenError = nil
	}

	// try to unmarshal data into InvalidAPIKeyError
	err = newStrictDecoder(data).Decode(&dst.InvalidAPIKeyError)
	if err == nil {
		jsonInvalidAPIKeyError, _ := json.Marshal(dst.InvalidAPIKeyError)
		if string(jsonInvalidAPIKeyError) == "{}" { // empty struct
			dst.InvalidAPIKeyError = nil
		} else {
			match++
		}
	} else {
		dst.InvalidAPIKeyError = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AccessForbiddenAccountStateError = nil
		dst.AccessForbiddenError = nil
		dst.InvalidAPIKeyError = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(GetCatalog403Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(GetCatalog403Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetCatalog403Response) MarshalJSON() ([]byte, error) {
	if src.AccessForbiddenAccountStateError != nil {
		return json.Marshal(&src.AccessForbiddenAccountStateError)
	}

	if src.AccessForbiddenError != nil {
		return json.Marshal(&src.AccessForbiddenError)
	}

	if src.InvalidAPIKeyError != nil {
		return json.Marshal(&src.InvalidAPIKeyError)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetCatalog403Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AccessForbiddenAccountStateError != nil {
		return obj.AccessForbiddenAccountStateError
	}

	if obj.AccessForbiddenError != nil {
		return obj.AccessForbiddenError
	}

	if obj.InvalidAPIKeyError != nil {
		return obj.InvalidAPIKeyError
	}

	// all schemas are nil
	return nil
}

type NullableGetCatalog403Response struct {
	value *GetCatalog403Response
	isSet bool
}

func (v NullableGetCatalog403Response) Get() *GetCatalog403Response {
	return v.value
}

func (v *NullableGetCatalog403Response) Set(val *GetCatalog403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCatalog403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCatalog403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCatalog403Response(val *GetCatalog403Response) *NullableGetCatalog403Response {
	return &NullableGetCatalog403Response{value: val, isSet: true}
}

func (v NullableGetCatalog403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCatalog403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


