#!/usr/bin/env bash
set -e

# ─── Colours ────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}!${NC} $1"; }
info() { echo -e "${CYAN}→${NC} $1"; }
fail() { echo -e "${RED}✗${NC} $1"; exit 1; }

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env.local"

echo ""
echo -e "${CYAN}rolls — local dev setup${NC}"
echo "─────────────────────────────────"
echo ""

# ─── Prerequisites ───────────────────────────────────────────────────────────
command -v node  >/dev/null 2>&1 || fail "node not found — install Node.js 20+"
command -v npm   >/dev/null 2>&1 || fail "npm not found"
command -v psql  >/dev/null 2>&1 || fail "psql not found — install PostgreSQL"
command -v createdb >/dev/null 2>&1 || fail "createdb not found — install PostgreSQL"
ok "Prerequisites OK"

# ─── .env.local ──────────────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
  warn ".env.local already exists — skipping creation"
else
  info "Creating .env.local with local dev defaults"

  JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  API_KEY=$(node -e "console.log('rk_' + require('crypto').randomBytes(24).toString('hex'))")

  cat > "$ENV_FILE" <<EOF
# Local development — generated by scripts/setup.sh

DATABASE_URL=postgres://localhost/rolls_dev

# WebAuthn — must be localhost for local dev
JWT_SECRET=${JWT_SECRET}
WEBAUTHN_RP_NAME=Rolls
WEBAUTHN_RP_ID=localhost
WEBAUTHN_ORIGIN=http://localhost:3000

# CLI auth
API_KEY=${API_KEY}

# Web password (leave empty to disable)
WEB_PASSWORD=

# R2 storage (leave empty to skip contact sheet uploads locally)
R2_ACCOUNT_ID=
R2_ACCESS_KEY_ID=
R2_SECRET_ACCESS_KEY=
R2_BUCKET=
R2_PUBLIC_URL=

APP_URL=http://localhost:3000

# Redis (leave empty to disable rate limiting locally)
REDIS_URL=
EOF

  ok "Created .env.local"
  echo ""
  warn "API_KEY set to: ${API_KEY}"
  warn "Add this to ~/.config/rolls/config.yml as web_app_api_key if you want the CLI to talk to local dev"
  echo ""
fi

# ─── Database ────────────────────────────────────────────────────────────────
if psql -lqt 2>/dev/null | cut -d '|' -f1 | grep -qw rolls_dev; then
  ok "Database rolls_dev already exists"
else
  info "Creating database rolls_dev"
  createdb rolls_dev
  ok "Created database rolls_dev"
fi

# ─── Dependencies ────────────────────────────────────────────────────────────
if [ -d "$ROOT/node_modules" ]; then
  ok "node_modules already installed"
else
  info "Installing npm dependencies"
  npm install --prefix "$ROOT"
fi

# ─── Migrations ──────────────────────────────────────────────────────────────
info "Running database migrations"
npm run migrate --prefix "$ROOT"

# ─── Done ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}All done!${NC}"
echo ""
echo "  Start the dev server:  npm run dev"
echo "  Open the app:          http://localhost:3000"
echo "  Register first user:   http://localhost:3000/register"
echo ""
