/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddAssetsToAlbum201ResponseErrorsInner struct for AddAssetsToAlbum201ResponseErrorsInner
type AddAssetsToAlbum201ResponseErrorsInner struct {
	Id *string `json:"id,omitempty"`
	HttpStatus *int32 `json:"http_status,omitempty"`
	Code *int32 `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	Subtype *string `json:"subtype,omitempty"`
	Errors *AddAssetsToAlbum201ResponseErrorsInnerErrors `json:"errors,omitempty"`
}

// NewAddAssetsToAlbum201ResponseErrorsInner instantiates a new AddAssetsToAlbum201ResponseErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAssetsToAlbum201ResponseErrorsInner() *AddAssetsToAlbum201ResponseErrorsInner {
	this := AddAssetsToAlbum201ResponseErrorsInner{}
	return &this
}

// NewAddAssetsToAlbum201ResponseErrorsInnerWithDefaults instantiates a new AddAssetsToAlbum201ResponseErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAssetsToAlbum201ResponseErrorsInnerWithDefaults() *AddAssetsToAlbum201ResponseErrorsInner {
	this := AddAssetsToAlbum201ResponseErrorsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AddAssetsToAlbum201ResponseErrorsInner) SetId(v string) {
	o.Id = &v
}

// GetHttpStatus returns the HttpStatus field value if set, zero value otherwise.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetHttpStatus() int32 {
	if o == nil || o.HttpStatus == nil {
		var ret int32
		return ret
	}
	return *o.HttpStatus
}

// GetHttpStatusOk returns a tuple with the HttpStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetHttpStatusOk() (*int32, bool) {
	if o == nil || o.HttpStatus == nil {
		return nil, false
	}
	return o.HttpStatus, true
}

// HasHttpStatus returns a boolean if a field has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) HasHttpStatus() bool {
	if o != nil && o.HttpStatus != nil {
		return true
	}

	return false
}

// SetHttpStatus gets a reference to the given int32 and assigns it to the HttpStatus field.
func (o *AddAssetsToAlbum201ResponseErrorsInner) SetHttpStatus(v int32) {
	o.HttpStatus = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetCode() int32 {
	if o == nil || o.Code == nil {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetCodeOk() (*int32, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *AddAssetsToAlbum201ResponseErrorsInner) SetCode(v int32) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AddAssetsToAlbum201ResponseErrorsInner) SetDescription(v string) {
	o.Description = &v
}

// GetSubtype returns the Subtype field value if set, zero value otherwise.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetSubtype() string {
	if o == nil || o.Subtype == nil {
		var ret string
		return ret
	}
	return *o.Subtype
}

// GetSubtypeOk returns a tuple with the Subtype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetSubtypeOk() (*string, bool) {
	if o == nil || o.Subtype == nil {
		return nil, false
	}
	return o.Subtype, true
}

// HasSubtype returns a boolean if a field has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) HasSubtype() bool {
	if o != nil && o.Subtype != nil {
		return true
	}

	return false
}

// SetSubtype gets a reference to the given string and assigns it to the Subtype field.
func (o *AddAssetsToAlbum201ResponseErrorsInner) SetSubtype(v string) {
	o.Subtype = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetErrors() AddAssetsToAlbum201ResponseErrorsInnerErrors {
	if o == nil || o.Errors == nil {
		var ret AddAssetsToAlbum201ResponseErrorsInnerErrors
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) GetErrorsOk() (*AddAssetsToAlbum201ResponseErrorsInnerErrors, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *AddAssetsToAlbum201ResponseErrorsInner) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given AddAssetsToAlbum201ResponseErrorsInnerErrors and assigns it to the Errors field.
func (o *AddAssetsToAlbum201ResponseErrorsInner) SetErrors(v AddAssetsToAlbum201ResponseErrorsInnerErrors) {
	o.Errors = &v
}

func (o AddAssetsToAlbum201ResponseErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.HttpStatus != nil {
		toSerialize["http_status"] = o.HttpStatus
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Subtype != nil {
		toSerialize["subtype"] = o.Subtype
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	return json.Marshal(toSerialize)
}

type NullableAddAssetsToAlbum201ResponseErrorsInner struct {
	value *AddAssetsToAlbum201ResponseErrorsInner
	isSet bool
}

func (v NullableAddAssetsToAlbum201ResponseErrorsInner) Get() *AddAssetsToAlbum201ResponseErrorsInner {
	return v.value
}

func (v *NullableAddAssetsToAlbum201ResponseErrorsInner) Set(val *AddAssetsToAlbum201ResponseErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAssetsToAlbum201ResponseErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAssetsToAlbum201ResponseErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAssetsToAlbum201ResponseErrorsInner(val *AddAssetsToAlbum201ResponseErrorsInner) *NullableAddAssetsToAlbum201ResponseErrorsInner {
	return &NullableAddAssetsToAlbum201ResponseErrorsInner{value: val, isSet: true}
}

func (v NullableAddAssetsToAlbum201ResponseErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAssetsToAlbum201ResponseErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


