/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InvaildRequestMissingParameterErrors struct for InvaildRequestMissingParameterErrors
type InvaildRequestMissingParameterErrors struct {
	Parameter []string `json:"parameter,omitempty"`
}

// NewInvaildRequestMissingParameterErrors instantiates a new InvaildRequestMissingParameterErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvaildRequestMissingParameterErrors() *InvaildRequestMissingParameterErrors {
	this := InvaildRequestMissingParameterErrors{}
	return &this
}

// NewInvaildRequestMissingParameterErrorsWithDefaults instantiates a new InvaildRequestMissingParameterErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvaildRequestMissingParameterErrorsWithDefaults() *InvaildRequestMissingParameterErrors {
	this := InvaildRequestMissingParameterErrors{}
	return &this
}

// GetParameter returns the Parameter field value if set, zero value otherwise.
func (o *InvaildRequestMissingParameterErrors) GetParameter() []string {
	if o == nil || o.Parameter == nil {
		var ret []string
		return ret
	}
	return o.Parameter
}

// GetParameterOk returns a tuple with the Parameter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvaildRequestMissingParameterErrors) GetParameterOk() ([]string, bool) {
	if o == nil || o.Parameter == nil {
		return nil, false
	}
	return o.Parameter, true
}

// HasParameter returns a boolean if a field has been set.
func (o *InvaildRequestMissingParameterErrors) HasParameter() bool {
	if o != nil && o.Parameter != nil {
		return true
	}

	return false
}

// SetParameter gets a reference to the given []string and assigns it to the Parameter field.
func (o *InvaildRequestMissingParameterErrors) SetParameter(v []string) {
	o.Parameter = v
}

func (o InvaildRequestMissingParameterErrors) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Parameter != nil {
		toSerialize["parameter"] = o.Parameter
	}
	return json.Marshal(toSerialize)
}

type NullableInvaildRequestMissingParameterErrors struct {
	value *InvaildRequestMissingParameterErrors
	isSet bool
}

func (v NullableInvaildRequestMissingParameterErrors) Get() *InvaildRequestMissingParameterErrors {
	return v.value
}

func (v *NullableInvaildRequestMissingParameterErrors) Set(val *InvaildRequestMissingParameterErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableInvaildRequestMissingParameterErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableInvaildRequestMissingParameterErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvaildRequestMissingParameterErrors(val *InvaildRequestMissingParameterErrors) *NullableInvaildRequestMissingParameterErrors {
	return &NullableInvaildRequestMissingParameterErrors{value: val, isSet: true}
}

func (v NullableInvaildRequestMissingParameterErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvaildRequestMissingParameterErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


