/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PutAssetExternalXmpDevelopSettingRequest struct for PutAssetExternalXmpDevelopSettingRequest
type PutAssetExternalXmpDevelopSettingRequest struct {
	// External xmp/develop link of source asset.
	FileHref *string `json:"file_href,omitempty"`
}

// NewPutAssetExternalXmpDevelopSettingRequest instantiates a new PutAssetExternalXmpDevelopSettingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutAssetExternalXmpDevelopSettingRequest() *PutAssetExternalXmpDevelopSettingRequest {
	this := PutAssetExternalXmpDevelopSettingRequest{}
	return &this
}

// NewPutAssetExternalXmpDevelopSettingRequestWithDefaults instantiates a new PutAssetExternalXmpDevelopSettingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutAssetExternalXmpDevelopSettingRequestWithDefaults() *PutAssetExternalXmpDevelopSettingRequest {
	this := PutAssetExternalXmpDevelopSettingRequest{}
	return &this
}

// GetFileHref returns the FileHref field value if set, zero value otherwise.
func (o *PutAssetExternalXmpDevelopSettingRequest) GetFileHref() string {
	if o == nil || o.FileHref == nil {
		var ret string
		return ret
	}
	return *o.FileHref
}

// GetFileHrefOk returns a tuple with the FileHref field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutAssetExternalXmpDevelopSettingRequest) GetFileHrefOk() (*string, bool) {
	if o == nil || o.FileHref == nil {
		return nil, false
	}
	return o.FileHref, true
}

// HasFileHref returns a boolean if a field has been set.
func (o *PutAssetExternalXmpDevelopSettingRequest) HasFileHref() bool {
	if o != nil && o.FileHref != nil {
		return true
	}

	return false
}

// SetFileHref gets a reference to the given string and assigns it to the FileHref field.
func (o *PutAssetExternalXmpDevelopSettingRequest) SetFileHref(v string) {
	o.FileHref = &v
}

func (o PutAssetExternalXmpDevelopSettingRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.FileHref != nil {
		toSerialize["file_href"] = o.FileHref
	}
	return json.Marshal(toSerialize)
}

type NullablePutAssetExternalXmpDevelopSettingRequest struct {
	value *PutAssetExternalXmpDevelopSettingRequest
	isSet bool
}

func (v NullablePutAssetExternalXmpDevelopSettingRequest) Get() *PutAssetExternalXmpDevelopSettingRequest {
	return v.value
}

func (v *NullablePutAssetExternalXmpDevelopSettingRequest) Set(val *PutAssetExternalXmpDevelopSettingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutAssetExternalXmpDevelopSettingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutAssetExternalXmpDevelopSettingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutAssetExternalXmpDevelopSettingRequest(val *PutAssetExternalXmpDevelopSettingRequest) *NullablePutAssetExternalXmpDevelopSettingRequest {
	return &NullablePutAssetExternalXmpDevelopSettingRequest{value: val, isSet: true}
}

func (v NullablePutAssetExternalXmpDevelopSettingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutAssetExternalXmpDevelopSettingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


