/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// GetAssetExternalXmpDevelopSetting403Response - struct for GetAssetExternalXmpDevelopSetting403Response
type GetAssetExternalXmpDevelopSetting403Response struct {
	AccessForbiddenError *AccessForbiddenError
	InvalidAPIKeyError *InvalidAPIKeyError
}

// AccessForbiddenErrorAsGetAssetExternalXmpDevelopSetting403Response is a convenience function that returns AccessForbiddenError wrapped in GetAssetExternalXmpDevelopSetting403Response
func AccessForbiddenErrorAsGetAssetExternalXmpDevelopSetting403Response(v *AccessForbiddenError) GetAssetExternalXmpDevelopSetting403Response {
	return GetAssetExternalXmpDevelopSetting403Response{
		AccessForbiddenError: v,
	}
}

// InvalidAPIKeyErrorAsGetAssetExternalXmpDevelopSetting403Response is a convenience function that returns InvalidAPIKeyError wrapped in GetAssetExternalXmpDevelopSetting403Response
func InvalidAPIKeyErrorAsGetAssetExternalXmpDevelopSetting403Response(v *InvalidAPIKeyError) GetAssetExternalXmpDevelopSetting403Response {
	return GetAssetExternalXmpDevelopSetting403Response{
		InvalidAPIKeyError: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetAssetExternalXmpDevelopSetting403Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AccessForbiddenError
	err = newStrictDecoder(data).Decode(&dst.AccessForbiddenError)
	if err == nil {
		jsonAccessForbiddenError, _ := json.Marshal(dst.AccessForbiddenError)
		if string(jsonAccessForbiddenError) == "{}" { // empty struct
			dst.AccessForbiddenError = nil
		} else {
			match++
		}
	} else {
		dst.AccessForbiddenError = nil
	}

	// try to unmarshal data into InvalidAPIKeyError
	err = newStrictDecoder(data).Decode(&dst.InvalidAPIKeyError)
	if err == nil {
		jsonInvalidAPIKeyError, _ := json.Marshal(dst.InvalidAPIKeyError)
		if string(jsonInvalidAPIKeyError) == "{}" { // empty struct
			dst.InvalidAPIKeyError = nil
		} else {
			match++
		}
	} else {
		dst.InvalidAPIKeyError = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AccessForbiddenError = nil
		dst.InvalidAPIKeyError = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(GetAssetExternalXmpDevelopSetting403Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(GetAssetExternalXmpDevelopSetting403Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetAssetExternalXmpDevelopSetting403Response) MarshalJSON() ([]byte, error) {
	if src.AccessForbiddenError != nil {
		return json.Marshal(&src.AccessForbiddenError)
	}

	if src.InvalidAPIKeyError != nil {
		return json.Marshal(&src.InvalidAPIKeyError)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetAssetExternalXmpDevelopSetting403Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AccessForbiddenError != nil {
		return obj.AccessForbiddenError
	}

	if obj.InvalidAPIKeyError != nil {
		return obj.InvalidAPIKeyError
	}

	// all schemas are nil
	return nil
}

type NullableGetAssetExternalXmpDevelopSetting403Response struct {
	value *GetAssetExternalXmpDevelopSetting403Response
	isSet bool
}

func (v NullableGetAssetExternalXmpDevelopSetting403Response) Get() *GetAssetExternalXmpDevelopSetting403Response {
	return v.value
}

func (v *NullableGetAssetExternalXmpDevelopSetting403Response) Set(val *GetAssetExternalXmpDevelopSetting403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAssetExternalXmpDevelopSetting403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAssetExternalXmpDevelopSetting403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAssetExternalXmpDevelopSetting403Response(val *GetAssetExternalXmpDevelopSetting403Response) *NullableGetAssetExternalXmpDevelopSetting403Response {
	return &NullableGetAssetExternalXmpDevelopSetting403Response{value: val, isSet: true}
}

func (v NullableGetAssetExternalXmpDevelopSetting403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAssetExternalXmpDevelopSetting403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


