/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MaintenanceError struct for MaintenanceError
type MaintenanceError struct {
	Code *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	Subtype *string `json:"subtype,omitempty"`
}

// NewMaintenanceError instantiates a new MaintenanceError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMaintenanceError() *MaintenanceError {
	this := MaintenanceError{}
	return &this
}

// NewMaintenanceErrorWithDefaults instantiates a new MaintenanceError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMaintenanceErrorWithDefaults() *MaintenanceError {
	this := MaintenanceError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *MaintenanceError) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceError) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *MaintenanceError) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *MaintenanceError) SetCode(v string) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MaintenanceError) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceError) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MaintenanceError) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MaintenanceError) SetDescription(v string) {
	o.Description = &v
}

// GetSubtype returns the Subtype field value if set, zero value otherwise.
func (o *MaintenanceError) GetSubtype() string {
	if o == nil || o.Subtype == nil {
		var ret string
		return ret
	}
	return *o.Subtype
}

// GetSubtypeOk returns a tuple with the Subtype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceError) GetSubtypeOk() (*string, bool) {
	if o == nil || o.Subtype == nil {
		return nil, false
	}
	return o.Subtype, true
}

// HasSubtype returns a boolean if a field has been set.
func (o *MaintenanceError) HasSubtype() bool {
	if o != nil && o.Subtype != nil {
		return true
	}

	return false
}

// SetSubtype gets a reference to the given string and assigns it to the Subtype field.
func (o *MaintenanceError) SetSubtype(v string) {
	o.Subtype = &v
}

func (o MaintenanceError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Subtype != nil {
		toSerialize["subtype"] = o.Subtype
	}
	return json.Marshal(toSerialize)
}

type NullableMaintenanceError struct {
	value *MaintenanceError
	isSet bool
}

func (v NullableMaintenanceError) Get() *MaintenanceError {
	return v.value
}

func (v *NullableMaintenanceError) Set(val *MaintenanceError) {
	v.value = val
	v.isSet = true
}

func (v NullableMaintenanceError) IsSet() bool {
	return v.isSet
}

func (v *NullableMaintenanceError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMaintenanceError(val *MaintenanceError) *NullableMaintenanceError {
	return &NullableMaintenanceError{value: val, isSet: true}
}

func (v NullableMaintenanceError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMaintenanceError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


