/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ForbiddenClientError struct for ForbiddenClientError
type ForbiddenClientError struct {
	Code *int32 `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	Links *ForbiddenClientErrorLinks `json:"links,omitempty"`
}

// NewForbiddenClientError instantiates a new ForbiddenClientError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForbiddenClientError() *ForbiddenClientError {
	this := ForbiddenClientError{}
	return &this
}

// NewForbiddenClientErrorWithDefaults instantiates a new ForbiddenClientError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForbiddenClientErrorWithDefaults() *ForbiddenClientError {
	this := ForbiddenClientError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ForbiddenClientError) GetCode() int32 {
	if o == nil || o.Code == nil {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForbiddenClientError) GetCodeOk() (*int32, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ForbiddenClientError) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *ForbiddenClientError) SetCode(v int32) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ForbiddenClientError) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForbiddenClientError) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ForbiddenClientError) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ForbiddenClientError) SetDescription(v string) {
	o.Description = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ForbiddenClientError) GetLinks() ForbiddenClientErrorLinks {
	if o == nil || o.Links == nil {
		var ret ForbiddenClientErrorLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForbiddenClientError) GetLinksOk() (*ForbiddenClientErrorLinks, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ForbiddenClientError) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given ForbiddenClientErrorLinks and assigns it to the Links field.
func (o *ForbiddenClientError) SetLinks(v ForbiddenClientErrorLinks) {
	o.Links = &v
}

func (o ForbiddenClientError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableForbiddenClientError struct {
	value *ForbiddenClientError
	isSet bool
}

func (v NullableForbiddenClientError) Get() *ForbiddenClientError {
	return v.value
}

func (v *NullableForbiddenClientError) Set(val *ForbiddenClientError) {
	v.value = val
	v.isSet = true
}

func (v NullableForbiddenClientError) IsSet() bool {
	return v.isSet
}

func (v *NullableForbiddenClientError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForbiddenClientError(val *ForbiddenClientError) *NullableForbiddenClientError {
	return &NullableForbiddenClientError{value: val, isSet: true}
}

func (v NullableForbiddenClientError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForbiddenClientError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


