/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetHealth403Response struct for GetHealth403Response
type GetHealth403Response struct {
	Code *int32 `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewGetHealth403Response instantiates a new GetHealth403Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetHealth403Response() *GetHealth403Response {
	this := GetHealth403Response{}
	return &this
}

// NewGetHealth403ResponseWithDefaults instantiates a new GetHealth403Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetHealth403ResponseWithDefaults() *GetHealth403Response {
	this := GetHealth403Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetHealth403Response) GetCode() int32 {
	if o == nil || o.Code == nil {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth403Response) GetCodeOk() (*int32, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetHealth403Response) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *GetHealth403Response) SetCode(v int32) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetHealth403Response) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth403Response) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetHealth403Response) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetHealth403Response) SetDescription(v string) {
	o.Description = &v
}

func (o GetHealth403Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableGetHealth403Response struct {
	value *GetHealth403Response
	isSet bool
}

func (v NullableGetHealth403Response) Get() *GetHealth403Response {
	return v.value
}

func (v *NullableGetHealth403Response) Set(val *GetHealth403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetHealth403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetHealth403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetHealth403Response(val *GetHealth403Response) *NullableGetHealth403Response {
	return &NullableGetHealth403Response{value: val, isSet: true}
}

func (v NullableGetHealth403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetHealth403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


