/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CreateAlbum400Response - struct for CreateAlbum400Response
type CreateAlbum400Response struct {
	InvaildRequestJSON *InvaildRequestJSON
	InvaildRequestPayload *InvaildRequestPayload
}

// InvaildRequestJSONAsCreateAlbum400Response is a convenience function that returns InvaildRequestJSON wrapped in CreateAlbum400Response
func InvaildRequestJSONAsCreateAlbum400Response(v *InvaildRequestJSON) CreateAlbum400Response {
	return CreateAlbum400Response{
		InvaildRequestJSON: v,
	}
}

// InvaildRequestPayloadAsCreateAlbum400Response is a convenience function that returns InvaildRequestPayload wrapped in CreateAlbum400Response
func InvaildRequestPayloadAsCreateAlbum400Response(v *InvaildRequestPayload) CreateAlbum400Response {
	return CreateAlbum400Response{
		InvaildRequestPayload: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateAlbum400Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into InvaildRequestJSON
	err = newStrictDecoder(data).Decode(&dst.InvaildRequestJSON)
	if err == nil {
		jsonInvaildRequestJSON, _ := json.Marshal(dst.InvaildRequestJSON)
		if string(jsonInvaildRequestJSON) == "{}" { // empty struct
			dst.InvaildRequestJSON = nil
		} else {
			match++
		}
	} else {
		dst.InvaildRequestJSON = nil
	}

	// try to unmarshal data into InvaildRequestPayload
	err = newStrictDecoder(data).Decode(&dst.InvaildRequestPayload)
	if err == nil {
		jsonInvaildRequestPayload, _ := json.Marshal(dst.InvaildRequestPayload)
		if string(jsonInvaildRequestPayload) == "{}" { // empty struct
			dst.InvaildRequestPayload = nil
		} else {
			match++
		}
	} else {
		dst.InvaildRequestPayload = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.InvaildRequestJSON = nil
		dst.InvaildRequestPayload = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(CreateAlbum400Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(CreateAlbum400Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateAlbum400Response) MarshalJSON() ([]byte, error) {
	if src.InvaildRequestJSON != nil {
		return json.Marshal(&src.InvaildRequestJSON)
	}

	if src.InvaildRequestPayload != nil {
		return json.Marshal(&src.InvaildRequestPayload)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateAlbum400Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.InvaildRequestJSON != nil {
		return obj.InvaildRequestJSON
	}

	if obj.InvaildRequestPayload != nil {
		return obj.InvaildRequestPayload
	}

	// all schemas are nil
	return nil
}

type NullableCreateAlbum400Response struct {
	value *CreateAlbum400Response
	isSet bool
}

func (v NullableCreateAlbum400Response) Get() *CreateAlbum400Response {
	return v.value
}

func (v *NullableCreateAlbum400Response) Set(val *CreateAlbum400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAlbum400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAlbum400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAlbum400Response(val *CreateAlbum400Response) *NullableCreateAlbum400Response {
	return &NullableCreateAlbum400Response{value: val, isSet: true}
}

func (v NullableCreateAlbum400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAlbum400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


