/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InvaildRequestPayloadErrors struct for InvaildRequestPayloadErrors
type InvaildRequestPayloadErrors struct {
	PayloadKeySubkey []string `json:"payload.&lt;key&gt;.&lt;subkey&gt;,omitempty"`
}

// NewInvaildRequestPayloadErrors instantiates a new InvaildRequestPayloadErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvaildRequestPayloadErrors() *InvaildRequestPayloadErrors {
	this := InvaildRequestPayloadErrors{}
	return &this
}

// NewInvaildRequestPayloadErrorsWithDefaults instantiates a new InvaildRequestPayloadErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvaildRequestPayloadErrorsWithDefaults() *InvaildRequestPayloadErrors {
	this := InvaildRequestPayloadErrors{}
	return &this
}

// GetPayloadKeySubkey returns the PayloadKeySubkey field value if set, zero value otherwise.
func (o *InvaildRequestPayloadErrors) GetPayloadKeySubkey() []string {
	if o == nil || o.PayloadKeySubkey == nil {
		var ret []string
		return ret
	}
	return o.PayloadKeySubkey
}

// GetPayloadKeySubkeyOk returns a tuple with the PayloadKeySubkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvaildRequestPayloadErrors) GetPayloadKeySubkeyOk() ([]string, bool) {
	if o == nil || o.PayloadKeySubkey == nil {
		return nil, false
	}
	return o.PayloadKeySubkey, true
}

// HasPayloadKeySubkey returns a boolean if a field has been set.
func (o *InvaildRequestPayloadErrors) HasPayloadKeySubkey() bool {
	if o != nil && o.PayloadKeySubkey != nil {
		return true
	}

	return false
}

// SetPayloadKeySubkey gets a reference to the given []string and assigns it to the PayloadKeySubkey field.
func (o *InvaildRequestPayloadErrors) SetPayloadKeySubkey(v []string) {
	o.PayloadKeySubkey = v
}

func (o InvaildRequestPayloadErrors) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PayloadKeySubkey != nil {
		toSerialize["payload.&lt;key&gt;.&lt;subkey&gt;"] = o.PayloadKeySubkey
	}
	return json.Marshal(toSerialize)
}

type NullableInvaildRequestPayloadErrors struct {
	value *InvaildRequestPayloadErrors
	isSet bool
}

func (v NullableInvaildRequestPayloadErrors) Get() *InvaildRequestPayloadErrors {
	return v.value
}

func (v *NullableInvaildRequestPayloadErrors) Set(val *InvaildRequestPayloadErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableInvaildRequestPayloadErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableInvaildRequestPayloadErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvaildRequestPayloadErrors(val *InvaildRequestPayloadErrors) *NullableInvaildRequestPayloadErrors {
	return &NullableInvaildRequestPayloadErrors{value: val, isSet: true}
}

func (v NullableInvaildRequestPayloadErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvaildRequestPayloadErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


