/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InvaildRequestRenditionType struct for InvaildRequestRenditionType
type InvaildRequestRenditionType struct {
	Errors *InvaildRequestRenditionTypeErrors `json:"errors,omitempty"`
	Code *int32 `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewInvaildRequestRenditionType instantiates a new InvaildRequestRenditionType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvaildRequestRenditionType() *InvaildRequestRenditionType {
	this := InvaildRequestRenditionType{}
	return &this
}

// NewInvaildRequestRenditionTypeWithDefaults instantiates a new InvaildRequestRenditionType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvaildRequestRenditionTypeWithDefaults() *InvaildRequestRenditionType {
	this := InvaildRequestRenditionType{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *InvaildRequestRenditionType) GetErrors() InvaildRequestRenditionTypeErrors {
	if o == nil || o.Errors == nil {
		var ret InvaildRequestRenditionTypeErrors
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvaildRequestRenditionType) GetErrorsOk() (*InvaildRequestRenditionTypeErrors, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *InvaildRequestRenditionType) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given InvaildRequestRenditionTypeErrors and assigns it to the Errors field.
func (o *InvaildRequestRenditionType) SetErrors(v InvaildRequestRenditionTypeErrors) {
	o.Errors = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *InvaildRequestRenditionType) GetCode() int32 {
	if o == nil || o.Code == nil {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvaildRequestRenditionType) GetCodeOk() (*int32, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *InvaildRequestRenditionType) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *InvaildRequestRenditionType) SetCode(v int32) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InvaildRequestRenditionType) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvaildRequestRenditionType) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InvaildRequestRenditionType) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InvaildRequestRenditionType) SetDescription(v string) {
	o.Description = &v
}

func (o InvaildRequestRenditionType) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableInvaildRequestRenditionType struct {
	value *InvaildRequestRenditionType
	isSet bool
}

func (v NullableInvaildRequestRenditionType) Get() *InvaildRequestRenditionType {
	return v.value
}

func (v *NullableInvaildRequestRenditionType) Set(val *InvaildRequestRenditionType) {
	v.value = val
	v.isSet = true
}

func (v NullableInvaildRequestRenditionType) IsSet() bool {
	return v.isSet
}

func (v *NullableInvaildRequestRenditionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvaildRequestRenditionType(val *InvaildRequestRenditionType) *NullableInvaildRequestRenditionType {
	return &NullableInvaildRequestRenditionType{value: val, isSet: true}
}

func (v NullableInvaildRequestRenditionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvaildRequestRenditionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


