/*
Lightroom API Documentation

Lightroom API Documentation, made available through [adobe.io](https://developer.adobe.com). API Change Logs are available [here](https://developer.adobe.com/lightroom/lightroom-api-docs/release-notes/).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ForbiddenClientErrorLinks struct for ForbiddenClientErrorLinks
type ForbiddenClientErrorLinks struct {
	RelsClientApp *ForbiddenClientErrorLinksRelsClientApp `json:"/rels/client_app,omitempty"`
}

// NewForbiddenClientErrorLinks instantiates a new ForbiddenClientErrorLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForbiddenClientErrorLinks() *ForbiddenClientErrorLinks {
	this := ForbiddenClientErrorLinks{}
	return &this
}

// NewForbiddenClientErrorLinksWithDefaults instantiates a new ForbiddenClientErrorLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForbiddenClientErrorLinksWithDefaults() *ForbiddenClientErrorLinks {
	this := ForbiddenClientErrorLinks{}
	return &this
}

// GetRelsClientApp returns the RelsClientApp field value if set, zero value otherwise.
func (o *ForbiddenClientErrorLinks) GetRelsClientApp() ForbiddenClientErrorLinksRelsClientApp {
	if o == nil || o.RelsClientApp == nil {
		var ret ForbiddenClientErrorLinksRelsClientApp
		return ret
	}
	return *o.RelsClientApp
}

// GetRelsClientAppOk returns a tuple with the RelsClientApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForbiddenClientErrorLinks) GetRelsClientAppOk() (*ForbiddenClientErrorLinksRelsClientApp, bool) {
	if o == nil || o.RelsClientApp == nil {
		return nil, false
	}
	return o.RelsClientApp, true
}

// HasRelsClientApp returns a boolean if a field has been set.
func (o *ForbiddenClientErrorLinks) HasRelsClientApp() bool {
	if o != nil && o.RelsClientApp != nil {
		return true
	}

	return false
}

// SetRelsClientApp gets a reference to the given ForbiddenClientErrorLinksRelsClientApp and assigns it to the RelsClientApp field.
func (o *ForbiddenClientErrorLinks) SetRelsClientApp(v ForbiddenClientErrorLinksRelsClientApp) {
	o.RelsClientApp = &v
}

func (o ForbiddenClientErrorLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RelsClientApp != nil {
		toSerialize["/rels/client_app"] = o.RelsClientApp
	}
	return json.Marshal(toSerialize)
}

type NullableForbiddenClientErrorLinks struct {
	value *ForbiddenClientErrorLinks
	isSet bool
}

func (v NullableForbiddenClientErrorLinks) Get() *ForbiddenClientErrorLinks {
	return v.value
}

func (v *NullableForbiddenClientErrorLinks) Set(val *ForbiddenClientErrorLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableForbiddenClientErrorLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableForbiddenClientErrorLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForbiddenClientErrorLinks(val *ForbiddenClientErrorLinks) *NullableForbiddenClientErrorLinks {
	return &NullableForbiddenClientErrorLinks{value: val, isSet: true}
}

func (v NullableForbiddenClientErrorLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForbiddenClientErrorLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


